#!/bin/bash
# Description: Report Top 10 processes are high Memory utilization
# Example result
# =====================================================================================
#   |%MEM   |       %CPU    |       PID     |       COMMAND
#   |3.3    |       6.1     |       8442    |       /usr/lib/firefox/firefox
#   |2.6    |       0.6     |       11445   |       /home/opsuser/.vscode/extensions/hashicorp.terraform-2.22.0-linux-x64/bin/terraform-ls
#   |2.5    |       0.9     |       9093    |       /usr/lib/firefox/firefox
#   |2.3    |       17.0    |       8952    |       /usr/lib/firefox/firefox
#   |2.1    |       3.9     |       3631    |       savscand
#   |2.0    |       1.5     |       4521    |       /opt/google/chrome/chrome
#   |2.0    |       1.2     |       3779    |       /usr/bin/gnome-shell
#   |1.9    |       4.2     |       11262   |       /snap/code/97/usr/share/code/code
#   |1.8    |       1.8     |       4269    |       /usr/lib/slack/slack


LIMIT_RESULT=10

rc=$(ps -eo %mem,pcpu,pid,args | sort -k 1 -r | head -${LIMIT_RESULT})
echo "$rc" | awk -v OFS='\t''|''\t' '{print"|" $1,$2,$3,$4}'
